### ISSUE TITLE
Feature: ReadFile and WriteFile

### ISSUE THREAD

**Issue by RednibCoding** [Farbfinsternis/jBB#1]
File reading and writing would be really handy.
It could be as simple as just writing and reading the whole file as pure text.
No fancy stuff like ReadByte, WriteInt etc., just read in a whole file into a js string and writing a whole file from js string.
Something like:

```
var text = 'This is a text';
WriteFile('test.txt', text);

var myText = ReadFile('test.txt');
```

**Comment by Farbfinsternis** [comment]
reading/writing files will coming, but with the limitations of the local storage.

**Comment by RednibCoding** [comment]
Do you mean the local hard-drive?

**Comment by Farbfinsternis** [comment]
`window.localStorage()`
see: [https://developer.mozilla.org/de/docs/Web/API/Window/localStorage](url)

**Comment by RednibCoding** [comment]
Ah OK sure. That OK.
