### ISSUE TITLE
Feature: Sound

### ISSUE THREAD

**Issue by RednibCoding** [Farbfinsternis/jBB#2]
Having the ability to play sound/music would be great.
For example 4 simple functions:

- LoadSound(path)
- PlaySound(sound)
- StopSound(sound)
- IsSoundPlaying(sound)

**Example:**
```
var mySound = LoadSound(path);
PlaySound(mySound);
if(IsSoundPlaying(mySound))
{
    StopSound(mySound)
}
```

It doesn't have to support dozend of sound formats, i think one would be enough.

**Comment by Farbfinsternis** [comment]
i'am working on this issues
