### ISSUE TITLE
Bug: Uneven image dimension causes certain frames not showing

### ISSUE THREAD

**Issue by RednibCoding** [Farbfinsternis/jBB#5]
When loading a spritesheet, and the spritesheet has uneven dimension (like the ship.png in examples: 93x80) then drawing certain frames with DrawImage, e.g. DrawImage(ship, x, y, 3), causes frames not beeing drawn.
I think this is caused when calculating the cellsPerRow and the tilePos.

**Comment by Farbfinsternis** [comment]
probably fixed ...
